version: '3'

services:
  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - internal_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    networks:
      - internal_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./start.sh
    volumes:
      - .:/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env
    networks:
      - internal_network

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python -m celery -A config worker -l info"
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env
    networks:
      - internal_network

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    ports:
      - "${RABBITMQ_PORT_1}:5672"
      - "${RABBITMQ_PORT_2}:15672"
    environment:
        - "RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}"
        - "RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    networks:
      - internal_network

volumes:
  mariadb_data:
  rabbitmq_data:

networks:
  internal_network:
    driver: bridge