version: '3'

services:
  db:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - internal_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - internal_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./start.sh
    volumes:
      - .:/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env
    networks:
      - internal_network

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python -m celery -A config worker -l info"
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env
    networks:
      - internal_network

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    ports:
      - "${RABBITMQ_PORT_1}:5672"
      - "${RABBITMQ_PORT_2}:15672"
    environment:
        - "RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}"
        - "RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    networks:
      - internal_network

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  internal_network:
    driver: bridge