# Generated by Django 4.2 on 2023-04-18 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.IntegerField(db_column='CPF')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(db_column='CEP', max_length=250)),
                ('logradouro', models.CharField(max_length=250)),
                ('bairro', models.CharField(max_length=250)),
                ('localidade', models.CharField(max_length=250)),
                ('numero', models.CharField(max_length=50)),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('padrao', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(blank=True, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('email_enviado', models.IntegerField(blank=True, null=True)),
                ('cod_cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loja.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('codigo', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoProduto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cod_pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loja.pedido')),
                ('cod_produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loja.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteEndereco',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('default', models.IntegerField(blank=True, null=True)),
                ('cod_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loja.cliente')),
                ('cod_endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loja.endereco')),
            ],
        ),
    ]
