# Generated by Django 4.2 on 2023-04-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.IntegerField(db_column='CPF')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteEndereco',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('default', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_cliente_endereco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(db_column='CEP', max_length=250)),
                ('logradouro', models.CharField(max_length=250)),
                ('bairro', models.CharField(max_length=250)),
                ('localidade', models.CharField(max_length=250)),
                ('numero', models.CharField(max_length=50)),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_endereco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(blank=True, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('email_enviado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PedidoProduto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tbl_pedido_produto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('codigo', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'tbl_produto',
                'managed': False,
            },
        ),
    ]
