# Generated by Django 4.2 on 2023-04-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='padrao',
        ),
    ]
