# Generated by Django 4.2 on 2023-04-18 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_remove_endereco_padrao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteendereco',
            name='cod_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='loja.cliente'),
        ),
        migrations.AlterField(
            model_name='clienteendereco',
            name='cod_endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='loja.endereco'),
        ),
        migrations.AlterField(
            model_name='clienteendereco',
            name='default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='clienteendereco',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cod_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loja.cliente'),
        ),
        migrations.AlterField(
            model_name='pedidoproduto',
            name='cod_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loja.pedido'),
        ),
        migrations.AlterField(
            model_name='pedidoproduto',
            name='cod_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loja.produto'),
        ),
        migrations.AlterField(
            model_name='pedidoproduto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
