# Generated by Django 4.2 on 2023-04-19 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_produto_titulo_alter_cliente_cpf_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clienteendereco',
            unique_together={('cod_cliente', 'cod_endereco')},
        ),
    ]
