# Generated by Django 4.2 on 2023-04-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_alter_clienteendereco_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteendereco',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
