# Generated by Django 4.2 on 2023-04-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_alter_endereco_cep_alter_endereco_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='email_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
